### ISSUE TITLE
Razor Components Project

### ISSUE THREAD

**Issue by LorenDorez** [Blazored/Menu#1]
When i install this nuget the 2 files `BlazoredMenuItem.razor` and `BlazoredSubMenu.razor` get droppped to the root. Not a big issue but i had to change the submenu to use the Full Namespace as it was causing an error

`
@inherits Blazored.Menu.BlazoredSubMenuBase
`

**Comment by LorenDorez** [comment]
I added to the View Imports but i think this is because in an RC project  it gets dropped in the root and not under `/Componenets`

**Comment by chrissainty** [comment]
Ok, this one was weird. It turns out if you have .razor files in a Blazor library project then they get copied into the project that installs the nuget package. 

I've changed the extension back to .cshtml and everything is back to normal. This fix is in version 1.0.1.
