### ISSUE TITLE
Issue with submenu on the server app

### ISSUE THREAD

**Issue by peterblazejewicz** [Blazored/Menu#13]
I've tried this also under the 3.1.0 Preview 2 there is a still a problem:

- the first submenu seems to be not rendering correctly. The nested content does not render within `li` submenu node
- the second submenu renders fine.

![menu-bug-host](https://user-images.githubusercontent.com/14539/68249427-17b5d480-001f-11ea-9706-d0e3c1b4fc0f.gif)

TBI

**Comment by aarondcoleman** [comment]
Also noticing the same thing. The `IEnumerable<MenuItem>` collection is apparently not populated in that mode.

**Comment by aarondcoleman** [comment]
I figured it out... you need to wrap the sub menu items in `<MenuTemplate>....</MenuTemplate>` like the documentation example. So:
```csharp
<BlazoredSubMenu Header="Sub Menu">
        <MenuTemplate>
            <BlazoredMenuItem>
                <NavLink href="counter">Counter</NavLink>
            </BlazoredMenuItem>
            <BlazoredMenuItem>
                <NavLink href="fetchdata">Fetch data</NavLink>
            </BlazoredMenuItem>
        </MenuTemplate>
    </BlazoredSubMenu>
```

**Comment by chrissainty** [comment]
Thanks for spotting that one @aarondcoleman. I've updated the sample in the repo
