### ISSUE TITLE
How to display menu correctly?

### ISSUE THREAD

**Issue by Oleg26Dev** [Blazored/Menu#18]
Hi Chris, 
I have created the start Blazor app, installed Blazoerd.Menu Nuget and want to replace the VS generated menu with Blazored.Menu.
What is wrong? How to change the font color?
I have added the 
<link href="_content/Blazored.Menu/blazored-menu.css" rel="stylesheet" />
to the _Host.cshtml.

I have attached the screenshot
![BlazoredMenu](https://user-images.githubusercontent.com/25686753/77222896-d3ebe380-6b57-11ea-8c4d-f931b1fed26f.PNG)

There is the NavMenu.razor, there is old menu left too to compare.

[NavMenu.razor.txt](https://github.com/Blazored/Menu/files/4362634/NavMenu.razor.txt)

**Comment by chrissainty** [comment]
Hi @Oleg26Dev, you just need to override the CSS styles with the settings you want such as the text colour. You can view the default CSS classes [here](https://github.com/Blazored/Menu/blob/master/src/Blazored.Menu/wwwroot/blazored-menu.css).

**Comment by fauxtix** [comment]
Hi Chris,

Is it possible to expand/collapse sub-menus in code?
For instance, I would like to have a sub-menu expanded after login to an app.

Thanks in advance.
Fausto
