### ISSUE TITLE
Renamed styles.css

### ISSUE THREAD

**Issue by LorenDorez** [Blazored/Menu#2]
It might be worth renaming styles.css so when they fix the static files issue it doesnt have conflicts. and or place in a Blazore.Menu folder

**Comment by chrissainty** [comment]
I'm not sure how the static file includes work, I've used a couple of the blazored libraries before in the same project and they both had CSS files called _styles_ and there wasn't a conflict.

I'm going to rename anyway as I think it will make it easier for people to see where certain styles are coming from.
